### ISSUE TITLE
Nil error at line 948

### ISSUE THREAD

**Issue by aaronbkarp** [develephant/mod_parse#1]
It looks like the block at line 946 should appear _after_ the block at line 955. The variable 'e' is guaranteed to be nil when line 948 executes (because of line 933). And even if it wasn't, it would be overwritten by line 955 anyway. I'm brand new to using this library so I might be wrong, but I tested this locally and it worked.

**Comment by develephant** [comment]
Hi,

That area has been needing a refactor for a while.  2.1.3 has been pushed.

Thanks.
