### ISSUE TITLE
cannot use '<' or '>' or '~=' with query tables !

### ISSUE THREAD

**Issue by MShawaf** [develephant/mod_parse#10]
Hi, currently using this : 

local queryTable = { 
  ["where"] = { ["score"] = 100 }
}
parse:getObjects( "score", queryTable, onGetObjects )

but obviously this this not enough, It's better to use something like this : 

local queryTable = { 
  ["where"] = { ["score"] > 100 }
}

so I can only get scores that are larger than 100

is there a way to do it ? or is there going to be ? :)

thanks.

**Comment by develephant** [comment]
A newer version has been released. Closing. 

[parse.develephant.com](http://parse.develephant.com)
