### ISSUE TITLE
(Serious) typo in getting started guide?

### ISSUE THREAD

**Issue by aaronbkarp** [develephant/mod_parse#2]
A few times the following line appears in the docs: `parse.dispatcher:addEventListener( "parseRequest", onParseResponse )`

I think it should be `"parseResponse"` not `"parseRequest"` -- as written, the listener is never called. Checked the source code, tested the change, and it works only with `"parseResponse"`.

**Comment by develephant** [comment]
Fixed.  Thanks for the report!

Cheers.
