### ISSUE TITLE
2.1.3 create object does not send back any callback info

### ISSUE THREAD

**Issue by scottrules44** [develephant/mod_parse#3]
2.1.3 create object does not send back any callback info

**Comment by develephant** [comment]
Hi,

Tests seem to indicate that it is working properly.

``` lua
parse:createObject('Cat', { age = 3, name = "Jiggles" }, function(e)
  print(e.response.objectId)
  print(e.response.createdAt)
end)
```

Output:
`Jul 25 15:32:02.706: DIviN06xvH`
`Jul 25 15:32:02.707: 2015-07-25T20:32:02.657Z`

You can turn on the `parse.showStatus = true` flag to show some errors you might be receiving from Parse.

Could you provide a test case/example?

Thanks.

https://github.com/develephant/mod_parse/wiki/Parse-Module-Docs#objects

**Comment by scottrules44** [comment]
Found problem try to get event.error

parse:createObject('Cat', { age = 3, name = "Jiggles" }, function(e)

if not e.error then

```
    print(e.response.objectId)

    print(e.response.createdAt)
```

else
print("problem")
end

end)

**Comment by scottrules44** [comment]
It not just for create try get and other stuff event.error is not working
for me was that removed?

**Comment by scottrules44** [comment]
Have your been able to reproduce this bug?

**Comment by develephant** [comment]
Hi,

Still looking into the issue.  Had a few reports that turning off showStatus has helped.  Sorry for delay.

Cheers.

**Comment by develephant** [comment]
This should be fixed.  Open a new issue otherwise.

Cheers.
