### ISSUE TITLE
Documentation Errors 

### ISSUE THREAD

**Issue by hicay** [develephant/mod_parse#4]
# Documentation Errors
## Parse:loginUser Usage:

``` lua
 local function onLoginUser( event )
   if not event.error then
     print( event.response.sessionToken )
   end
 end
 parse:onLoginUser( { ["username"] = "Chris", ["password"] = "strongpw" }, onLoginUser )
```

parse:~~onLoginUser~~( { ["username"] = "Chris", ["password"] = "strongpw" }, onLoginUser )
###### Correct One:

parse:loginUser( { ["username"] = "Casay", ["password"] = "1234" }, onLoginUser )  
## Parse:getMe Usage:

``` lua
 local function onGetMe( event )
   if event.code == parse.EXPIRED then
     print( "Session expired.  Log in.")
   else
     print( "Hello", event.response.username )
   end
 end
 parse:getUser( onGetMe )
```

parse:~~getUser~~( onGetMe )
###### Correct One:

parse:getMe( onGetMe )

**Comment by develephant** [comment]
Thank you for taking the time to let me know.  All fixed up.

Cheers.
