### ISSUE TITLE
Linkedfile

### ISSUE THREAD

**Issue by Keithhol13** [develephant/mod_parse#7]
Not a really big deal but I have noticed when calling the call back function of the linked file does not call the call back function even though it works. And yes, the functions are the same name. If I turn on the show status it shows me that the link file went through. And all I did is put the link file in side the first if statement of the upload file. If you would like to test it.

**Comment by develephant** [comment]
I will take a look.  Thanks for reporting.

**Comment by develephant** [comment]
Hi,

Please test the latest release, [mod_parse 2.2.4](https://github.com/develephant/mod_parse) and let me know if that helps.

Cheers.

**Comment by Keithhol13** [comment]
Sorry took so long to reply everythng is working great. You do an amazing job I hope to be a great programmer like you one day.

**Comment by Keithhol13** [comment]
One thing that I did change in you code was for the file to be written into a folder when downloaded, took me a while to figure out where to put it but finally found it. Maybe a comment in the notes about this might help people who want the file in a certain folder.

**Comment by develephant** [comment]
A newer version has been released. Closing. 

[parse.develephant.com](http://parse.develephant.com)
