### ISSUE TITLE
Runtime error when getting session error

### ISSUE THREAD

**Issue by gaara629** [develephant/mod_parse#8]
How's it going Develephant!

I just wanted to make aware that when I try logging in with the wrong account information, the response is resulting in a run time error. Before, you had it as if not event.error if successful, and when an error occurs it was if event.error. But any time I get a session error the program just hangs and does nothing. When I look into the console I get this error:

Runtime error
 C:\Users\user\Downloads\Upload and link file\Upload and link file\mod_parse.lua:1051: attempt to index field 'response' (a nil value)
stack traceback:

 C:\Users\user\Downloads\Upload and link file\Upload and link file\mod_parse.lua:1051: in function 'onResponse'
 C:\Users\user\Downloads\Upload and link file\Upload and link file\mod_parse.lua:844: in function <C:\Users\user\Downloads\Upload and link file\Upload and link file\mod_parse.lua:844>

This fix is crucial for my code. I use multiple servers and actually rely on session errors. I just wanted to point this out to you. Here is some code as an example:

local parse = require( "mod_parse" )
parse:init({ 
  appId = "", 
  apiKey = "",
})

--parse.showStatus = true

local userObjId 
local fileObjId 
local userId
local function onLoginUserWindows( event )

   if not event.error then
     userId = event.response.objectId

```
 local filemeta = { ["filename"] = "", ["baseDir"] = system.DocumentsDirectory}

local function onUpload( event )
   if event.name == "parseResponse" then --uploaded
     print( event.response.name, event.response.url )
     fileObjId = event.response.name

  local function onFileLinked( event )
        if not event.error then
             print( event.response.updatedAt )
        end
  end

  parse:linkFile(parse.USER, userId, "Mydata",  fileObjId, onFileLinked) 

  elseif event.name == "parseProgress" then --uploading
    print( event.bytesTransferred )
   end
end
```

   parse:uploadFile(filemeta, onUpload)

   elseif event.error then
      print("bad")
    end
  end

 parse:loginUser( { ["username"] = "", ["password"] = ""}, onLoginUserWindows )

When I put in the incorrect information, it never goes to the else statement and prints to the console. It just throws an error. Thanks for reading!

**Comment by develephant** [comment]
Hi,

Let me see what's going on.  What version of the mod are you using?

**Comment by develephant** [comment]
Hello,

 I believe I have fixed the issue in the latest [**mod_parse 2.2.4**](https://github.com/develephant/mod_parse), but additionally, I wanted talk a little about best practices when using the module.

First I should point out that `linkFile()` is missing a value.  You need to send both the `fileRef` _and_ `fileUrl`. It looks like you're missing the `fileUrl`. Though this is a separate issue from the `response` error you reported.

I'm not sure what column type you're using on Parse, but the `File` type is what you should be using when creating the column to link a file to.

In general, best practice is to separate out your event calls as much as possible. Also, though counter-intuitive, you should work your way up in your event returns.

Anyway, I put together a "recipe" for this that demonstrates a 'best practices' methodology. You can find it [here](https://github.com/develephant/mod_parse/wiki/Recipes:-mod_parse).

Please test and let me know if this has resolved your issue.

Cheers.

**Comment by gaara629** [comment]
Sorry about that! Should have checked sooner for a response. I was using 2.2.3, but 2.2.4 corrected the error. Thanks for your time! I just took a look at your example and that helps a ton. I really appreciate your time.

**Comment by develephant** [comment]
A newer version has been released. Closing. 

[parse.develephant.com](http://parse.develephant.com)
