### ISSUE TITLE
parse:getMe( onGetMe )

### ISSUE THREAD

**Issue by MShawaf** [develephant/mod_parse#9]
local parse = require("mod_parse")
parse:init({
appId = "....",
apiKey = "...."
})

parse.showStatus = true

--count event
--parse:appOpened()
--parse:logEvent( "Share", { ["screen"] = "splash" } )
--parse:logEvent( "Share", { ["screen"] = "results" } )

local function onCreateUser( event )
  print( event.response.createdAt )
  print( event.response.sessionToken )
end

local userData = { ["username"] = "Ali", ["password"] = "121212" }
-- parse:createUser( userData, onCreateUser )

local function onLoginUser( event )
  if not event.error then
    print( event.response.objectId )

```
--check if user is verified
if event.response.emailVerified then
  --user is verified
end
```

  end
end

parse:loginUser( { ["username"] = "Ali", ["password"] = "121212" }, onLoginUser )

local function onGetMe( event )
  if event.code == parse.EXPIRED then
    print( "Session expired.  Log in.")
  else
    print( "Hello", event.response.username )
  end
end

parse:getMe( onGetMe )

error says : 
File: mod_parse.lua
Line: 568
User must be logged in first, sessionToken cannot be nil.

**Comment by develephant** [comment]
A newer version has been released. Closing. 

[parse.develephant.com](http://parse.develephant.com)
